site_name: exprint
site_url: https://exprint.readthedocs.io
site_description: exprint helps you explore data quickly by pretty-printing values with a flexible API.
site_author: Benjamin Bourbon

repo_url: https://github.com/bourbonut/exprint

theme:
  name: material
  # logo: images/logo.svg
  # favicon: images/favicon.svg
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.tabs.sticky
    - navigation.footer
    - content.code.annotate
    - content.code.copy
    - content.code.select

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true

plugins:
  search:
  mkdocstrings:
    default_handler: python
    handlers:
      python:
        options:
          show_root_heading: true
          docstring_style: numpy
          show_if_no_docstring: true
          show_docstring_attributes: false
          show_signature_annotations: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          separate_signature: true
          signature_crossrefs: true
          merge_init_into_class: true
          parameter_headings: true
          show_bases: false
          filters: ["!^_"]

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bourbonut/exprint/
      name: exprint on Github

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - javascript/customhl.js

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Guide: guide.md
  - Default functions: default.md
  - API:
    - api/index.md
    - api/exprint.md
    - "exprint.formatter":
      - api/formatter/format.md
      - api/formatter/formatter.md
      - api/formatter/format_class.md
      - api/formatter/format_color.md
      - api/formatter/format_dict.md
      - api/formatter/format_list.md
      - api/formatter/format_set.md
      - api/formatter/format_tuple.md
      - api/formatter/format_value.md
    - api/colors.md
 
copyright: Copyright &copy; bourbonut
